sudo: required
services:
  - docker

before_install: 
  - docker build -t legendsaini/docker-react -f Dockerfile.dev .

script: 
  - docker run legendsaini/docker-react npm run test -- --coverage

deploy:
  provider: "elastic-beanstalk"
  region: "us-east-1a"
  app: "docker"
  env: "Docker-env"
  on:
    branch: master